LOG_CODES = \
        {   
            "INVALID_INPUT_EQUATION_EQUAL": "❗ Error: La expresión de la ecuación no está bien definida.",
            "INVALID_INPUT_EQUATION_VAR" : "❗ Error: No se encuentran definidas variables.",
            "INVALID_EQUATION_VAR_NOT_APPEAR" : "❗ Error: La variable \"{}\" no se encuentra definida en la ecuación.",
            "INVALID_EQUATION_CONSTANT_NOT_APPEAR": "❗ Error: La constante \"{}\" no se encuentra definida en la ecuación.",
            "INVALID_EQUATION_FREE_SYMBS": "❗ Error: El símbolo \"{}\" no se encuentra definido como variable o constante.",
            "INVALID_EQUATION_DUP_SYMBS": "❗ Error: El símbolo \"{}\" se encuentra definido como variable y constante.",
            "INVALID_INPUT_COND_EXP": "❗ Error: La expresión de la condición no está bien definida.",
            "INVALID_INPUT_COND_MULTIPLE_OP": "❗ Error: La expresión de la condición contiene más de un operador: \"{}\".",
            "INVALID_INPUT_COND_VAR": "❗ Error: No se encuentran definidas variables.",
            "INVALID_INPUT_COND_ACT:" : "❗ Error: No se encuentran definidas acciones.",
            "INVALID_COND_FREE_SYMBS": "❗ Error: El símbolo \"{}\" no se encuentra definido como variable o constante.",
            "INVALID_COND_DUP_SYMBS": "❗ Error: El símbolo \"{}\" se encuentra definido como variable y constante.",
            "GENERATION_FAILED_NO_LANGUAGE": "❗ Error: No se ha definido el lenguaje de salida.",
            "GENERATION_FAILED_NO_OUTPUT": "❗ Error: No se ha definido la salida.",
            "GENERATION_FAILED_NO_EQUATIONS": "❗ Error: No se han definido ecuaciones.",
            "GENERATION_FAILED_MISSING_VARS": "❗ Error: Faltan por definir las ecuaciones de las variables \"{}\".",
            "GENERATION_FAILED_NO_COMPILER": "❗ Error: No se encuentran los paquetes necesarios \"{}\".",
            "GENERATION_ERROR": "❗ Error: La generación de código ha fallado.",
            "SUCCESS_ADD_EQUATION": "Éxito: Ecuacion_{}  añadida correctamente.",
            "SUCCESS_EDIT_EQUATION": "Éxito: Ecuacion_{} editada correctamente.",
            "SUCCESS_ADD_CONDITION": "Éxito: Condicion_{} añadida correctamente.",
            "SUCCESS_EDIT_CONDITION": "Éxito: Condicion_{} editada correctamente.",
            "GENERATION_SUCCESS": "Éxito: Generación de código \"{}\" exitosa.",   
        }